[package]
name = "minos"
version = "0.1.0"
edition = "2021"
authors = ["johnteper <git@johnteper.me>"]
description = "Authorization library"
homepage = "https://github.com/jonhteper/minos"
license = "MIT"
repository = "https://github.com/jonhteper/minos"

[profile.release]
lto = true

[dependencies]
heimdall_errors = "0.2.0"
chrono = "0.4.19"
jsonwebtoken = { version = "8.1.1", optional = true}
serde = { version="1.0.137", features = ["derive"], optional = true }
toml = {version = "0.5.9", optional = true }

[features]
jwt = ["jsonwebtoken", "serde"]
toml_storage = ["serde", "toml"]
